In [1]:
import numpy as np

let's declare a numpy array as shown below:

In [2]:
a = np.arange(27)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Reshaping the array in a 3 dimensional array:

In [4]:
a = a.reshape(3, 3, 3)

In [5]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

To access the 0th index of the outermost dimension, we use a[0], which returns:

In [6]:
a[0] 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

To access the 0th row of the outermost dimension, we use:

In [7]:
a[0, 0]

array([0, 1, 2])

To access the 0th element of the entire array, we use the index [0,0,0]

In [8]:
a[0, 0, 0]

0

Another way to index array is by using ellipsis (...) as shown below:

In [9]:
a[...]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
a[0, ...]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
a[0, 0, ...]

array([0, 1, 2])

When ellipsis is used with 0th index as shown below, we get all the elements from the 0th column:

In [12]:
a[..., 0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

However, ellipsis can only be used once during array indexing, as shown below:

In [17]:
a[..., 0, ...]

IndexError: an index can only have a single ellipsis ('...')

Colon (:) can be used to index/slice a numpy array. The syntax to use colon is [start:stop]. Similarly, the syntax for double colon (::) is [start:stop:step]. In the following example, we only specify the step size in our 3-dimensional array, therfore we get the outermost dimension at indices 0 and 2.

In [13]:
a[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
a[0, ::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [15]:
a[0, 0, ::2]

array([0, 2])

To index the 0th row of the outermost dimension, we can use the following syntax:

In [19]:
a[:, 0, :]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

Another way to get the same result is as follows:

In [20]:
a[..., 0, :]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

To index, every second row of the 3X3 array, we use the following syntax

In [21]:
a[:, ::2, :]

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [15, 16, 17]],

       [[18, 19, 20],
        [24, 25, 26]]])